logging:
    level:
        ROOT: INFO
        com.ca.mfaas: INFO
        org.springframework: WARN
        org.apache.catalina: WARN
        com.netflix: WARN
        com.netflix.discovery: ERROR
        com.netflix.config: ERROR
        com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient: OFF
        com.netflix.discovery.DiscoveryClient: OFF
        org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO

logbackServiceName: ZWEADC1

server:
    port: 10013
    servlet:
        contextPath: /discoverableclient
    ssl:
        enabled: true
        protocol: TLSv1.2
        enabled-protocols: TLSv1.2
        ciphers: ${apiml.security.ssl.ciphers}
        keyStoreType: PKCS12
        trustStoreType: PKCS12

spring:
    mvc:
        throw-exception-if-no-handler-found: true
    output:
        ansi:
            enabled: detect

management:
    endpoints:
        web:
            base-path: /application
            exposure:
                include: health,info,routes
    health:
        defaults:
            enabled: false

# The `apiml` node contains API Mediation Layer specific configuration
apiml:
    enabled: false
    service:
        # Following values are default values that can be changed by user:
        serviceId: discoverableclient
        title: Service Spring Integration Enabler sample application API©     #Copyright is for UTF8 encoding check
        description:  Sample API services to demonstrate Spring Integration Enabler
        catalogUiTile:
            id: cademoapps
            title: Sample API Mediation Layer Applications
            description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
            version: 1.0.0
        ssl:
            keyAlias: ${server.ssl.keyAlias}
            keyPassword: ${server.ssl.keyPassword}
            keyStore: ${server.ssl.keyStore}
            keyStorePassword: ${server.ssl.keyStorePassword}
            keyStoreType: ${server.ssl.keyStoreType}
            trustStore: ${server.ssl.trustStore}
            trustStorePassword: ${server.ssl.trustStorePassword}
            trustStoreType: ${server.ssl.trustStoreType}
        # Following values are provided by the developer:
        scheme: https
        baseUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${server.port}
        homePageRelativeUrl: ${server.servlet.contextPath}
        statusPageRelativeUrl: actuator/info
        healthCheckRelativeUrl: actuator/health
        routes:
            -   gatewayUrl: ui/v1
                serviceUrl: ${server.servlet.contextPath}
            -   gatewayUrl: api/v1
                serviceUrl: ${server.servlet.contextPath}/api/v1
            -   gatewayUrl: ws/v1
                serviceUrl: ${server.servlet.contextPath}/ws
        apiInfo:
            -   apiId: org.zowe.discoverableclient
                gatewayUrl: api/v1
                version: 1.0.0
                swaggerUrl: https://${apiml.service.hostname}:${server.port}${server.servlet.contextPath}/v2/api-docs
                documentationUrl: https://www.zowe.org
    security:
        ssl:
            ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

---
spring:
    profiles: diag

management:
    endpoints:
        web:
            base-path: /application
            exposure:
                include: "*"

---
spring:
    profiles: dev
    profiles.include:
        diag

logging:
    level:
        ROOT: INFO
        com.ca.mfaas: DEBUG
        org.springframework: INFO
        org.apache.catalina: INFO
        com.netflix: INFO


---
spring:
    profiles: diag

management:
    endpoints:
        web:
            base-path: /application
            exposure:
                include: "*"

---
spring:
    profiles: dev
    profiles.include:
        diag

logging:
    level:
        ROOT: INFO
        com.ca.mfaas: DEBUG
        org.springframework: INFO
        org.apache.catalina: INFO
        com.netflix: INFO
