spring.profiles.include: diag

environment:
    serviceId: DISCO-PLUG
    serviceTitle: API-ML Plugins PoC
    serviceDescription: Sample Spring Boot 2.x REST API Service - demonstrating APIML Plugin concept
    discoveryEnabled: true
    hostname: localhost
    port: 10035
    discoveryLocations: https://localhost:10011/eureka/
    ipAddress: 127.0.0.1

spring:
    output:
        ansi:
            enabled: always

server:
    ssl:
        enabled: false
        keyAlias: localhost
        keyPassword: password
        keyStore: keystore/localhost/localhost.keystore.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        trustStore: keystore/localhost/localhost.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12


eureka:
    instance:
        metadata-map:
            mfaas:
                plugin:
                    inbound: true # or outbound
                    async: false
                    extension-point: security # aka Type in Zool: most often defines the stage during the routing flow when the Filter will be applied (although it can be any custom string). One extension point allowed. Others points: logging, request pre-processing
                    exec-order: 1 # 1- first, 0 last; Subsequent replaces previous
                    criteria:
                    end-point: # One end point allowed  to be called in the processing chain gor given extension point
                        destination: validate/*
                        input:
                            payload: false
                            headers: true
                            authorization: false;
                            path: true
                            protocol: true
                            query: true
                        output:
                            headers: # Plugin will provide additional headers values
                                - X-APIML-PLUGIN-HEADER1
                                - X-APIML-PLUGIN-HEADER2
                            data: # Expect plugin to perform an action on input and
                                operation: delete # add, replace
                                value: $string
                        errors:
                            - ES_EP-${Extension_Point-ID}:
                            - ES_EP-#{}:
                            -

